### ISSUE TITLE
Supply additional password via script-args?

### ISSUE THREAD

**Issue by rufflabs** [nnposter/nndefaccts#13]
Is it possible to supply an additional password to check via a `--script-args`?

My use case is to run an nmap internally against our known deployed printers/scanners. However, we are also aware of some weak custom passwords that were previously deployed in the environment and want to check for those too. 

I see that `login_combos` variable is used to hold the username/password's to check. Would it be possible to make this something that can be appended to via a `--script-args`? I am not terribly well versed in lua, but if this is technically feasible I would love to make this a possibility.

**Comment by nnposter** [comment]
This is technically doable for the most part. The one issue is that some of the targets are behaving differently if a true default password is used, such as redirecting to a password change dialog, hard or soft, instead of starting a regular authenticated session. Handling such cases would require updating the fingerprint matching logic too, which is impractical.

Just to make sure I understand you correctly, you are not proposing to test additional usernames with passwords, but to try *existing* default usernames with additional passwords supplied separately, correct?

**Comment by rufflabs** [comment]
That is correct. In my particular use case this only applies to printers, as that's all I am interested in. Testing an additional known password against a printer/copier with the normal admin/default username. 

This may be pretty niche, and not useful to the masses. If that's the case, my fall back is to just manually edit the relevant fingerprint `login_combos` to add my additional password for my own use.

**Comment by nnposter** [comment]
The scenario is not quite fitting the intended use so I do not want to "pollute" the standard Nmap script. On the other hand, it should be relatively straightforward to handle this natively inside Lua, instead of having to edit the source code of individual fingerprints.

Append the following Lua fragment to the end of the fingerprint file and adjust the filename on the last line as needed.
```lua

local io = require "io"

local function expand_combos (fingerprints, filename)
  for pwd in io.lines(filename) do
    for _, fp in ipairs(fingerprints) do
      local combos = fp.login_combos
      local usernames = {}
      for _, combo in ipairs(combos) do
        if pwd == combo.password then
          usernames = {}
          break
        end
        usernames[combo.username] = 1
      end
      for usr in pairs(usernames) do
        table.insert(combos, {username = usr, password = pwd})
      end
    end
  end
end
        
expand_combos(fingerprints, "/tmp/my_passwords.txt")
```
This will dynamically modify all fingerprints one by one, enumerating existing fingerprint usernames and adding new username/password combinations from passwords in file `/tmp/my_passwords.txt`.
